### PR TITLE
AdminAccessLogin view page updated

### PR DESCRIPTION
**Pull request by israelCyabukombe**
A. I made the fields "MemberID" and "Password" required so that the user can only proceed after entering valid information. They can't click submit without filling in the fields
Files changed: - AdminAccessLogin.cshtml

B. Tested the AdminConsole login to make sure only the appropriate memberID can reach the adminConsole view page. i.e the only valid memberID with admin access is "2345678" and password "password"

C. Updated the AdminConsole View with Live data
Files changed: AdminConsoleController.cs
                       Admincontroller.cs
                      Index.cshtml

D. check the commits

### CODE REVIEW

**Comment by quazi-irfan** [comment]
Your other pull request #207 also makes similar changes to Index.cshtml file. Shouldn't you merge these two pull requests into one?

**Comment by sakurano92** [comment]
if you have similar two pull request, it have possibility of having merge conflict, go in to #207 in github and revert it to avoid merge conflicts.
IF requires both changes do not revert.

**Comment by AboodV2** [comment]
This pull request and the other pull request are similar .Also,you are not addressing dubeme comment on the previous pull request which is "But, for a good User Experience. If you're going to return the user to the login page again, it would be nice to have a message explaining why."

**Comment by israelCyabukombe** [comment]
@ AboodV2  I have addressed that issue that's why I put the required fields the user is not going anywhere without filling out the memberId and password. The view is not returning to the page anymore.

**Comment by israelCyabukombe** [comment]
@ sakurano92 and iamcreasy  I have closed the Pull request #207 since everything change In it is addressed in this one.

**Review by dubeme — APPROVED** [review]

**Pull request merged**
