### PR TITLE
Added Age to Create Account page

### PR DESCRIPTION
**Pull request by israelCyabukombe**

### CODE REVIEW

**Comment by quazi-irfan** [comment]
@israelCyabukombe you have to bring both the sleepy-hack/WAMA and israelCyabukombe/WAMA repo at the same state first before requesting a pull request.

Your sleepy-hack/WAMA fork has only [11 commits](https://github.com/israelCyabukombe/WAMA). It should have 115 commits.

**Comment by israelCyabukombe** [comment]
I tried syncing and I keep failing at it.


Israel

________________________________

**Comment by israelCyabukombe** [comment]
Check out my git status

 it says I'm ahead by 3 comits. but the git push fails


[cid:b052b6a0-8a30-418f-9f9f-7ebe31ad6cbf]


Israel Cyabukombe

________________________________

**Comment by quazi-irfan** [comment]
You have to push your local repo to your github repo first before you make a pull request. Otherwise your pull request will be always include unwanted commits.

One simple solution is to delete your wama repository and forking it again from sleep-hacks/WAMA.

**Comment by dubeme** [comment]
Israel, I can't accept this pull request. We've got to figure out why your machine isn't working well.

**Pull request closed without merging**
